---
- name: Update Known Hosts
  hosts: cluster
  become: true
  gather_facts: true

  tasks:
    - name: Ensure SSH directory exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.ssh"
        state: directory
        mode: '0700'

    - name: Ensure known_hosts file exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.ssh/known_hosts"
        state: touch
        mode: '0600'

    - name: Add GitHub Runner Public Key to known_hosts
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.ssh/known_hosts"
        create: yes
        line: "{{ runner_public_key }}"
      loop: "{{ groups['cluster'] }}"
